name: Run tests
on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API code
        uses: actions/checkout@v6
        with:
          repository: 'santiago120600/SpringBootLibraryAPI'
          ref: 'main'
          path: 'library-api'
      - name: Checkout test code
        uses: actions/checkout@v6
        with:
          path: 'tests'
      - name: Build and run API in Docker
        working-directory: ./library-api
        run: |
          docker compose -f docker/dev/docker-compose.yaml up --build -d
      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to start on http://localhost:8080..."

          for i in {1..30}; do
            if curl -s http://localhost:8080/api/v1/authors > /dev/null; then
              echo "API is up!"
              exit 0
            fi
            echo "Still waiting..."
            sleep 5
          done

          echo "API did not start in time"
          docker ps
          docker logs $(docker ps -q)
          exit 1
      - name: Build and run tests in Docker
        working-directory: ./tests
        run: |
          docker compose -f docker-compose.yaml up --build --abort-on-container-exit
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: |
            tests/target/reports